### ISSUE TITLE
GitHub problem in an organization

### ISSUE THREAD

**Issue by Neustradamus** [sjaeckel/sjaeckel.github.io#1]
Dear @sjaeckel,

I have a problem with libtom organization.

Can you look, I think that a bad manipulation has been done.

It is linked to CVE-2019-17362 which is not fixed yet, I think.

Thanks in advance.

**Comment by sjaeckel** [comment]
Thank you for opening an issue here. It shows even better how problematic working with you is. You report something unrelated in an open space you still have access to, in the hope to get some validation of your point of view.

Access to the libtom organization is fine, nothing bad happened there. You are simply blocked because working with you is toxic and I am not interested in your contribution. You behave like a micromanager and nobody likes them. You are micromanaging others, in their projects, without contributing anything else yourself.

Please stay away from me.
